name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache apt-install
      uses: daaku/gh-action-apt-install@v4
      with:
        packages: pkg-config libdbus-1-dev libssl-dev
    - name: Build
      run: cd akl-rs && cargo build --verbose
    - name: Run tests
      run: cd akl-rs && cargo test --verbose
