name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add pkg-config
      run: apt install pkg-config
    - name: Install libssl
      run: apt install libssl-dev
    - name: Install libdbus
      run: apt install libdbus-1-dev
    - name: Build
      run: cd akl-rs && cargo build --verbose
    - name: Run tests
      run: cd akl-rs && cargo test --verbose
