name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache apt-install pkg-config
      uses: daaku/gh-action-apt-install@v4
      with:
        packages: pkg-config
    - name: Cache apt-install libssl
      uses: daaku/gh-action-apt-install@v4
      with:
        packages: libssl-dev
    - name: Cache apt-install libdbus
      uses: daaku/gh-action-apt-install@v4
      with:
        packages: libdbus-1-dev
    - name: Build
      run: cd akl-rs && cargo build --verbose
    - name: Run tests
      run: cd akl-rs && cargo test --verbose
